version: "3.7"
services:

  hasura:
    image: hasura/graphql-engine:v1.3.2
    ports: 
      - 8080:8080
    environment: 
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=password
      - HASURA_GRAPHQL_AUTH_HOOK=https://alluring-coral-fur.glitch.me/simple/webhook
      - HASURA_ACTION_CREATE_QUESTION_URL=http://hasura-create-question
    depends_on:
      - "postgres"
    restart: always
  
  hasura-create-question:
    build:
      context: ./hasura/actions/create-question

  postgres:
    image: postgres:13
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres

volumes:
  db_data: